name: Update Poll Index

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'polls/**.md' # Only run if markdown files in polls/ change
      - '.github/workflows/update-index.yml' # Or if the workflow itself changes
      - 'scripts/generate-index.ts' # Or if the script changes
      - 'scripts/package.json'
      - 'scripts/tsconfig.json'

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow the job to commit changes

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a current LTS version
          cache: 'npm'
          cache-dependency-path: scripts/package-lock.json # Cache dependencies based on lock file

      - name: Install dependencies
        run: npm ci
        working-directory: ./scripts

      - name: Generate index.json
        run: npm run generate
        working-directory: ./scripts

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet polls/index.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add polls/index.json
          git commit -m "chore: Update poll index.json [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
