name: Update Governance Indexes

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      # Trigger on changes in polls or executive directories
      - 'polls/**.md'
      - 'executive-votes/**.md'
      # Trigger on changes to scripts or workflow
      - '.github/workflows/update-index.yml'
      - 'scripts/**.ts'
      - 'scripts/package.json'
      - 'scripts/tsconfig.json'

jobs:
  update-indexes: # Renamed job for clarity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          pnpm-version: 9 # Match the lockfile version (v9.0)
          cache: 'pnpm'
          cache-dependency-path: scripts/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Use pnpm install
        working-directory: ./scripts

      - name: Generate index files
        run: pnpm run generate:all # Use pnpm run
        working-directory: ./scripts

      - name: Check for changes in index files
        id: git-check
        run: |
          git diff --quiet polls/index.json executive-votes/index.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Add both index files if they exist and have changed
          git add polls/index.json executive-votes/index.json
          git commit -m "chore: Update governance index files [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
